name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [DEV, QA, PROD]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to ${{ matrix.environment }}
      env:
        ENVIRONMENT: ${{ matrix.environment }}
      run: |
        echo "Deploying to $ENVIRONMENT"
        # Comandos de deploy aqui

    environment:
      name: ${{ matrix.environment }}
      url: https://example.com  # ajuste conforme necessário